services:
  model-service:
    build:
      context: ./services/model-service
      dockerfile: Dockerfile
    container_name: job-search-model-service-dev
    ports:
      - "8001:8001"
    environment:
      - MODEL_PATH=${MODEL_PATH}
      - DATASET_PATH=${DATASET_PATH}
    volumes:
      - ./services/model-service/model:/app/model
      - ./services/mock-data/job_vacancy.csv:/app/dataset/job_vacancy.csv
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'
        reservations:
          memory: 2G
    restart: unless-stopped
    networks:
      - job-search-network

  backend-api:
    build:
      context: ./services/backend-api
      dockerfile: Dockerfile
    container_name: job-search-backend-api-dev
    ports:
      - "8000:8000"
    environment:
      - MODEL_SERVICE_URL=http://model-service:8001
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      # Mount source code for hot reloading
      - ./services/backend-api/main.py:/app/main.py
      - ./services/mock-data/:/app/mock-data
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - job-search-network

networks:
  job-search-network:
    driver: bridge 