version: '3.8'

services:
  backend:
    build: ./job-search-be
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./job-search-be:/app
      - /app/__pycache__
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network

  frontend:
    build: ./job-search-fe
    ports:
      - "3000:3000"
    environment:
      - NUXT_PUBLIC_API_BASE_URL=http://localhost:8000
    volumes:
      - ./job-search-fe:/app
      - /app/node_modules
      - /app/.nuxt
      - /app/.output
    depends_on:
      - backend
    command: pnpm dev --host 0.0.0.0
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 