services:
  backend:
    build: ./job-search-be
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    env_file:
      - ./job-search-be/.env  # Contains GOOGLE_API_KEY
    volumes:
      - ./job-search-be:/app
      - be_cache:/app/__pycache__     # Named volume for Python cache
      - be_venv:/app/venv            # Named volume for virtual environment
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  be_cache:
  be_venv: 