// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/15/2025, 5:11:37 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/cklee/dev/job-search-platform/services/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/cklee/dev/job-search-platform/services/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/cklee/dev/job-search-platform/services/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/cklee/dev/job-search-platform/services/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/cklee/dev/job-search-platform/services/frontend/plugins/**/*.{js,ts,mjs}","/Users/cklee/dev/job-search-platform/services/frontend/composables/**/*.{js,ts,mjs}","/Users/cklee/dev/job-search-platform/services/frontend/utils/**/*.{js,ts,mjs}","/Users/cklee/dev/job-search-platform/services/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/cklee/dev/job-search-platform/services/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/cklee/dev/job-search-platform/services/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/cklee/dev/job-search-platform/services/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;