/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./nuxt.config.{js,ts}",
    "./app.vue",
    "./assets/**/*.css",
    "./components/**/*.vue",
    "./pages/**/*.vue",
  ],
  safelist: [
    "animate-fade-in",
    "animate-slide-up",
    "animate-bounce-subtle",
    "animate-pulse",
    "animate-spin",
    "line-clamp-2",
    "line-clamp-3",
    "btn-primary",
    "btn-secondary",
    "btn-outline",
    "vertical-progress-step",
    "vertical-progress-connector",
    "focus-ring",
    "ring-2",
    "ring-4",
    "ring-primary-100",
    "ring-primary-500",
    "ring-offset-2",
    "transform",
    "transition-all",
    "transition-colors",
    "transition-transform",
    "duration-200",
    "duration-300",
    "duration-500",
    "ease-in-out",
    "ease-out",
    "hover:-translate-y-0.5",
    "hover:scale-105",
    "hover:shadow-medium",
    "hover:bg-primary-700",
    "hover:bg-gray-700",
    "rotate-180",
    "items-center",
    "items-start",
    "justify-center",
    "justify-between",
    "flex-col",
    "space-x-2",
    "space-x-3",
    "space-x-4",
    "space-y-1",
    "space-y-2",
    "space-y-3",
    "space-y-4",
    "break-words",
    "break-all",
    "whitespace-nowrap",
    "overflow-hidden",
    "relative",
    "absolute",
    "z-10",
    "z-50",
    "card",
    "card-header",
    "card-body",
    "upload-area",
    "upload-area.default",
    "upload-area.has-file",
    "section-preview",
    "section-header",
    "section-content",
    "stat-card",
    "stat-value",
    "stat-label",
    "edit-button",
    "editable-textarea",
    "backdrop-glass",
    "text-gradient",
    "shadow-soft",
    "shadow-medium",
    "shadow-strong",
    "shadow-glow",
    // Specific responsive utilities that we actually use
    "sm:w-10", "sm:w-12", "sm:h-10", "sm:h-12",
    "sm:text-sm", "sm:text-base", "sm:text-lg", "sm:text-xl", "sm:text-2xl",
    "sm:p-3", "sm:p-4", "sm:p-6", "sm:py-3", "sm:py-4", "sm:px-4", "sm:px-6",
    "sm:mb-3", "sm:mb-4", "sm:space-x-3", "sm:space-x-4", "sm:space-y-4",
    "sm:gap-4", "sm:gap-6", "sm:grid-cols-2", "sm:grid-cols-4",
    "sm:flex-row", "sm:items-center", "sm:min-h-[3.5rem]",
    "md:grid-cols-2", "md:flex-row",
    "lg:grid-cols-2", "lg:grid-cols-3", "lg:grid-cols-4", "lg:hidden", "lg:flex",
    "xl:grid-cols-3",
    // Min height utilities we actually use
    "min-h-[2.5rem]", "min-h-[3rem]", "min-h-[3.5rem]",
    "flex-shrink-0",
    "flex-1",
    "min-w-0",
    // Grid utilities
    "grid-cols-1", "grid-cols-2", "grid-cols-3", "grid-cols-4",
    "gap-3", "gap-4", "gap-6",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      colors: {
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
        gray: {
          50: '#f9fafb',
          100: '#f3f4f6',
          200: '#e5e7eb',
          300: '#d1d5db',
          400: '#9ca3af',
          500: '#6b7280',
          600: '#4b5563',
          700: '#374151',
          800: '#1f2937',
          900: '#111827',
        }
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'bounce-subtle': 'bounceSubtle 2s infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        bounceSubtle: {
          '0%, 20%, 50%, 80%, 100%': { transform: 'translateY(0)' },
          '40%': { transform: 'translateY(-3px)' },
          '60%': { transform: 'translateY(-2px)' },
        }
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
      },
      boxShadow: {
        'soft': '0 2px 15px -3px rgba(0, 0, 0, 0.07), 0 10px 20px -2px rgba(0, 0, 0, 0.04)',
        'medium': '0 4px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
        'strong': '0 10px 40px -10px rgba(0, 0, 0, 0.15), 0 2px 8px -2px rgba(0, 0, 0, 0.1)',
      }
    },
  },
  plugins: [],
} 